### ISSUE TITLE
After knocking out a user, the actions list still shows kicked user

### ISSUE THREAD

**Issue by rickatech** [rickatech/dungeon#1]

**Comment by rickatech** [comment]
This seems to be happening on stable v0.2.1 and development v0.2.3

**Comment by rickatech** [comment]
Okay, I think fix is in for dev v.0.2.3, please test!
https://portal.zaptech.org/dun_dev/

**Comment by henauker** [comment]
Confirmed fixed

**Comment by rickatech** [comment]
Okay, I'll push the fixed code to the stable web site at https://portal.zaptech.org/dungeon/, stay tuned!

**Comment by rickatech** [comment]
Closing.  Pushed release with feature fix to github master branch and stable link above .
